### ISSUE TITLE
The minimum api-level on which it would compile & run 

### ISSUE THREAD

**Issue by cg-cri-gl** [nightflame2/karma-firewall#2]
Thanks for opensourcing it - first off !

The short version: 
Two questions:
(1) would compilation work for api-19 (kitkat 4.4.2) work and would the app run ? and
(2) would i be able to achieve my goal (see following) with this app  - Thanks ?   

The slightly longer version:
To provide a little background : have a couple of kitkats 4.4.2 phones (api level 19) and am looking for a firewall (preferably a 'noroot' one, like yours - since i have a really hard time finding a way to root these phones (except _maybe_ king[o]rooT, which has malware) for purpose using them as hotspots (for laptop, ...) but restrict egress (outgoing connections)  to specific destination ip addresses.  

To add some info: before finding your app listed in [this list](https://android.izzysoft.de/applists/category/named/network_admin_firewall#group_377) - where it appeared only couple of days ago :) -   i've tried 'noroot fwall', but alas... when it is started (although without any blocking rule, but instead all whitelisted)  no device can **connect** anymore to hotspot - no ip address received =>  which either points to 
1. dhcp being rejected when app starts (ipTables?? - don't think so, since the app would require root access ? , or would the whole routing & firewalling be done by android's vpn framework ?) or 
2. dhcp not running on this new _tun_ interface , or 
3. some bug (?) refered to [here  ](https://github.com/M66B/NetGuard/blob/master/FAQ.md#user-content-faq22)

Tips are welcomed for allowing me to achieve what i want / need are appreciated , Thanks again !

**Comment by nightflame2** [comment]
It might complie for KitKat API19. But note VPN works differently for API below Build.VERSION_CODES.LOLLIPOP. Basically you cannot selectively firewall apps, its all or nothing.

My understanding is that Android VPNs do not work with HotSpots. All traffic from a device connected to the HotSpot just bypasses the VPN. Not sure what NoRoot Firewall is doing to break the HotSpot.

**Comment by cg-cri-gl** [comment]
Thanks for sharing your ideas... seems no success in said approach..
